### ISSUE TITLE
lowByte macro is broken since 2.4.0

### ISSUE THREAD

**Issue by oseiler2** [SpenceKonde/megaTinyCore#515]
Since updating to 2.4.0 I'm getting an error for using the lowByte macro:
Arduino IDE 1.8.13:
`\AppData\Local\Arduino15\packages\megaTinyCore\hardware\megaavr\2.4.0\cores\megatinycore/api/Common.h:70:18: error: 'w' was not declared in this scope
 #define lowByte (w) ((uint8_t) ((w)    &  0xff))
                  ^
\Local\Temp\arduino_modified_sketch_443879\sketch_sep02a.ino:2:3: note: in expansion of macro 'lowByte'
   lowByte(0xaa55);
   ^~~~~~~`

Platform.io:
`\.platformio\packages\framework-arduino-megaavr-megatinycore\cores\megatinycore/api/Common.h:70:18: error: 'w' was not declared in this scope
 #define lowByte (w) ((uint8_t) ((w)    &  0xff))
                  ^
src\main.cpp:310:20: note: in expansion of macro 'lowByte'
     c_payload[0] = lowByte(PROBE_INTERVAL);
                    ^~~~~~~`

The last commit on that file introduced a whitespace before the first bracket. Removing that fixes it for me.
`#define lowByte (w) ((uint8_t) ((w)    &  0xff))`

PR to follow.

**Comment by oseiler2** [comment]
... and yes I feel silly for relying on _a really silly hand-holding macro_ :-)
